package com.iit.mit.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PersonTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonTypeAllPropertiesEquals(PersonType expected, PersonType actual) {
        assertPersonTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertPersonTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonTypeAllUpdatablePropertiesEquals(PersonType expected, PersonType actual) {
        assertPersonTypeUpdatableFieldsEquals(expected, actual);
        assertPersonTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonTypeAutoGeneratedPropertiesEquals(PersonType expected, PersonType actual) {
        assertThat(expected)
            .as("Verify PersonType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonTypeUpdatableFieldsEquals(PersonType expected, PersonType actual) {
        assertThat(expected)
            .as("Verify PersonType relevant properties")
            .satisfies(e -> assertThat(e.getJobTitle()).as("check jobTitle").isEqualTo(actual.getJobTitle()))
            .satisfies(e -> assertThat(e.getRole()).as("check role").isEqualTo(actual.getRole()))
            .satisfies(e -> assertThat(e.getLevel()).as("check level").isEqualTo(actual.getLevel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonTypeUpdatableRelationshipsEquals(PersonType expected, PersonType actual) {}
}
